Steps

- pre - cleaning

  - ✂️ strip
  - 👥 replace
  - 🪚 split
  - 🔡 lowercase
  - 🔢 removing numbers
  - ❗️ removing punctuation and symbols
- preprocessing

  - 🎄 Tokenizing
  - 🛑 Removing stopwords
  - 🌐 Lemmatizing
-creating a pipline

-fit and tranform training/test/validation set with pipeline

-train naive bayrs model with train data

-validate model with validation set

-test model with test set

In [1]:
import pandas as pd
import nltk

Pre Cleaning the Data

In [2]:
path = "/home/ulrike/code/navaso93/liar_project/raw_data/liar/train.tsv"
df = pd.read_csv(path , sep='\t', header = 0)
df.head()

,2635.json,false,Says the Annies List political group supports third-trimester abortions on demand.,abortion,dwayne-bohac,State representative,Texas,republican,0,1,0.1,0.2,0.3,a mailer
0,10540.json,half-true,When did the decline of coal start? It started...,"energy,history,job-accomplishments",scott-surovell,State delegate,Virginia,democrat,0.0,0.0,1.0,1.0,0.0,a floor speech.
1,324.json,mostly-true,"Hillary Clinton agrees with John McCain ""by vo...",foreign-policy,barack-obama,President,Illinois,democrat,70.0,71.0,160.0,163.0,9.0,Denver
2,1123.json,false,Health care reform legislation is likely to ma...,health-care,blog-posting,NaN,NaN,none,7.0,19.0,3.0,5.0,44.0,a news release
3,9028.json,half-true,The economic turnaround started at the end of ...,"economy,jobs",charlie-crist,NaN,Florida,democrat,15.0,9.0,20.0,19.0,2.0,an interview on CNN
4,12465.json,true,The Chicago Bears have had more starting quart...,education,robin-vos,Wisconsin Assembly speaker,Wisconsin,republican,0.0,3.0,2.0,5.0,1.0,a an online opinion-piece

In [3]:
df.columns = ['id', 'label', 'statement', 'subject','speaker', "job_title", 'state', 'party', 'barely_true_counts', 'false_counts',
'half_true_counts', 'mostly_true_counts', 'pants_on_fire_counts','context']
df.head()

,id,label,statement,subject,speaker,job_title,state,party,barely_true_counts,false_counts,half_true_counts,mostly_true_counts,pants_on_fire_counts,context
0,10540.json,half-true,When did the decline of coal start? It started...,"energy,history,job-accomplishments",scott-surovell,State delegate,Virginia,democrat,0.0,0.0,1.0,1.0,0.0,a floor speech.
1,324.json,mostly-true,"Hillary Clinton agrees with John McCain ""by vo...",foreign-policy,barack-obama,President,Illinois,democrat,70.0,71.0,160.0,163.0,9.0,Denver
2,1123.json,false,Health care reform legislation is likely to ma...,health-care,blog-posting,NaN,NaN,none,7.0,19.0,3.0,5.0,44.0,a news release
3,9028.json,half-true,The economic turnaround started at the end of ...,"economy,jobs",charlie-crist,NaN,Florida,democrat,15.0,9.0,20.0,19.0,2.0,an interview on CNN
4,12465.json,true,The Chicago Bears have had more starting quart...,education,robin-vos,Wisconsin Assembly speaker,Wisconsin,republican,0.0,3.0,2.0,5.0,1.0,a an online opinion-piece

In [4]:
import string # "string" module is already installed with Python
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

def cleaning(sentence):

    # Basic cleaning
    sentence = sentence.strip() ## remove whitespaces
    sentence = sentence.lower() ## lowercase
    sentence = ''.join(char for char in sentence if not char.isdigit()) ## remove numbers

    # Advanced cleaning
    for punctuation in string.punctuation:
        sentence = sentence.replace(punctuation, '') ## remove punctuation

    tokenized_sentence = word_tokenize(sentence) ## tokenize
    stop_words = set(stopwords.words('english')) ## define stopwords

    tokenized_sentence_cleaned = [ ## remove stopwords
        w for w in tokenized_sentence if not w in stop_words
    ]

    lemmatized = [
        WordNetLemmatizer().lemmatize(word, pos = "v")
        for word in tokenized_sentence_cleaned
    ]

    cleaned_sentence = ' '.join(word for word in lemmatized)

    return cleaned_sentence

In [5]:
df["statement"] = df["statement"].apply(cleaning)
df.head()

,id,label,statement,subject,speaker,job_title,state,party,barely_true_counts,false_counts,half_true_counts,mostly_true_counts,pants_on_fire_counts,context
0,10540.json,half-true,decline coal start start natural gas take star...,"energy,history,job-accomplishments",scott-surovell,State delegate,Virginia,democrat,0.0,0.0,1.0,1.0,0.0,a floor speech.
1,324.json,mostly-true,hillary clinton agree john mccain vote give ge...,foreign-policy,barack-obama,President,Illinois,democrat,70.0,71.0,160.0,163.0,9.0,Denver
2,1123.json,false,health care reform legislation likely mandate ...,health-care,blog-posting,NaN,NaN,none,7.0,19.0,3.0,5.0,44.0,a news release
3,9028.json,half-true,economic turnaround start end term,"economy,jobs",charlie-crist,NaN,Florida,democrat,15.0,9.0,20.0,19.0,2.0,an interview on CNN
4,12465.json,true,chicago bear start quarterback last years tota...,education,robin-vos,Wisconsin Assembly speaker,Wisconsin,republican,0.0,3.0,2.0,5.0,1.0,a an online opinion-piece

In [6]:
df.dtypes

id                       object
label                    object
statement                object
subject                  object
speaker                  object
job_title                object
state                    object
party                    object
barely_true_counts      float64
false_counts            float64
half_true_counts        float64
mostly_true_counts      float64
pants_on_fire_counts    float64
context                  object
dtype: object

In [7]:
df["id"] = df["id"].str.replace(".json", "", regex=False)
df.head()

,id,label,statement,subject,speaker,job_title,state,party,barely_true_counts,false_counts,half_true_counts,mostly_true_counts,pants_on_fire_counts,context
0,10540,half-true,decline coal start start natural gas take star...,"energy,history,job-accomplishments",scott-surovell,State delegate,Virginia,democrat,0.0,0.0,1.0,1.0,0.0,a floor speech.
1,324,mostly-true,hillary clinton agree john mccain vote give ge...,foreign-policy,barack-obama,President,Illinois,democrat,70.0,71.0,160.0,163.0,9.0,Denver
2,1123,false,health care reform legislation likely mandate ...,health-care,blog-posting,NaN,NaN,none,7.0,19.0,3.0,5.0,44.0,a news release
3,9028,half-true,economic turnaround start end term,"economy,jobs",charlie-crist,NaN,Florida,democrat,15.0,9.0,20.0,19.0,2.0,an interview on CNN
4,12465,true,chicago bear start quarterback last years tota...,education,robin-vos,Wisconsin Assembly speaker,Wisconsin,republican,0.0,3.0,2.0,5.0,1.0,a an online opinion-piece

Vectorizing of the data
- using TfidfVectorizing

Key Paramaters
- max_df (min_df) can be either a float between 0.0 and 1.0 or an integer
- max_df (min_df) = 0.5  ⇔  "ignore terms that appear in more (less) than 50% of the documents"
- max_df (min_df) = 20  ⇔  "ignore terms that appear in more (less) than 20 documents"
- By default, max_df = 1.0  ⇔  no "frequent" word will be removed
- By default, min_df = 0.0  ⇔  no "infrequent" word will be removed
- ngram_range = (1, 1) 👉 (by default) will only capture the unigrams (single words)
- ngram_range = (1, 2) 👉 will capture the unigrams, and the bigrams
- ngram_range = (1, 3) 👉 will capture the unigrams, the bigrams, and the trigrams
- ngram_range = (2, 3) 👉 will capture the bigrams, and the trigrams but not the unigrams

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Instantiating the TfidfVectorizer
tf_idf_vectorizer = TfidfVectorizer()

# Training it on the texts
weighted_words = pd.DataFrame(tf_idf_vectorizer.fit_transform(df["statement"]).toarray(),
                 columns = tf_idf_vectorizer.get_feature_names_out())

weighted_words

,aa,aaa,aaron,aarp,abandon,abas,abbas,abbott,abc,abcs,...,zimmerman,zinn,zip,zippo,zombie,zombies,zone,zoo,zuckerberg,zuckerbergs
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10234,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10235,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10236,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10237,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10238,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10239 entries, 0 to 10238
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    10239 non-null  object
 1   label                 10239 non-null  object
 2   statement             10239 non-null  object
 3   subject               10237 non-null  object
 4   speaker               10237 non-null  object
 5   job_title             7341 non-null   object
 6   state                 8029 non-null   object
 7   party                 10237 non-null  object
 8   barely_true_counts    10237 non-null  float64
 9   false_counts          10237 non-null  float64
 10  half_true_counts      10237 non-null  float64
 11  mostly_true_counts    10237 non-null  float64
 12  pants_on_fire_counts  10237 non-null  float64
 13  context               10137 non-null  object
dtypes: float64(5), object(9)
memory usage: 1.1+ MB

In [10]:
import numpy as np

from sklearn.model_selection import cross_validate
from sklearn.pipeline import make_pipeline

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import recall_score

# Feature/Target
X = df["statement"]
y = df["label"]

# Pipeline vectorizer + Naive Bayes
pipeline_naive_bayes = make_pipeline(
    TfidfVectorizer(ngram_range = (1, 2)),
    MultinomialNB(alpha=0.1)
)

In [11]:
X.info()

<class 'pandas.core.series.Series'>
RangeIndex: 10239 entries, 0 to 10238
Series name: statement
Non-Null Count  Dtype
--------------  -----
10239 non-null  object
dtypes: object(1)
memory usage: 80.1+ KB

In [12]:
y.info()

<class 'pandas.core.series.Series'>
RangeIndex: 10239 entries, 0 to 10238
Series name: label
Non-Null Count  Dtype
--------------  -----
10239 non-null  object
dtypes: object(1)
memory usage: 80.1+ KB

In [13]:
# Cross-validation
cv_results = cross_validate(pipeline_naive_bayes, X, y, cv = 5, scoring = ["recall_macro"]) # recall_macro due to 5 classes
average_recall = cv_results["test_recall_macro"].mean()
np.round(average_recall,2)

np.float64(0.21)

Grid Search for the Vectorizer and the Naive Bayes Model

In [14]:
from sklearn.model_selection import GridSearchCV

# Define the grid of parameters
parameters = {
    'tfidfvectorizer__ngram_range': ((1,1), (2,2), (1,2), (1,3)),
    'multinomialnb__alpha': (0.1,1)
}

# Perform Grid Search
grid_search = GridSearchCV(
    pipeline_naive_bayes,
    parameters,
    scoring = "recall_macro",
    cv = 5,
    n_jobs=-1,
    verbose=1
)

grid_search.fit(X, y)

# Best score
print(f"Best Score = {grid_search.best_score_}")

# Best params
print(f"Best params = {grid_search.best_params_}")

Fitting 5 folds for each of 8 candidates, totalling 40 fits
Best Score = 0.21470723653208318
Best params = {'multinomialnb__alpha': 0.1, 'tfidfvectorizer__ngram_range': (1, 2)}

Pipeline with logistic regression

In [15]:
from sklearn.linear_model import LogisticRegression


pipeline_lr = make_pipeline(
    TfidfVectorizer(ngram_range=(1,2)),
    LogisticRegression(max_iter=2000, class_weight="balanced")
)

In [16]:
cv_results_lr = cross_validate(
    pipeline_lr, X, y, cv=5, scoring=["recall_macro"]
)

average_recall_lr = cv_results_lr["test_recall_macro"].mean()

In [17]:
average_recall_lr

np.float64(0.2476392037350527)

Comparison of roBERTa and deBERTa

In [18]:
# ! pip install transformers

In [19]:
path = "/home/ulrike/code/navaso93/liar_project/raw_data/liar/train.tsv"
df_bert = pd.read_csv(path , sep='\t', header = 0)
df_bert.head()

,2635.json,false,Says the Annies List political group supports third-trimester abortions on demand.,abortion,dwayne-bohac,State representative,Texas,republican,0,1,0.1,0.2,0.3,a mailer
0,10540.json,half-true,When did the decline of coal start? It started...,"energy,history,job-accomplishments",scott-surovell,State delegate,Virginia,democrat,0.0,0.0,1.0,1.0,0.0,a floor speech.
1,324.json,mostly-true,"Hillary Clinton agrees with John McCain ""by vo...",foreign-policy,barack-obama,President,Illinois,democrat,70.0,71.0,160.0,163.0,9.0,Denver
2,1123.json,false,Health care reform legislation is likely to ma...,health-care,blog-posting,NaN,NaN,none,7.0,19.0,3.0,5.0,44.0,a news release
3,9028.json,half-true,The economic turnaround started at the end of ...,"economy,jobs",charlie-crist,NaN,Florida,democrat,15.0,9.0,20.0,19.0,2.0,an interview on CNN
4,12465.json,true,The Chicago Bears have had more starting quart...,education,robin-vos,Wisconsin Assembly speaker,Wisconsin,republican,0.0,3.0,2.0,5.0,1.0,a an online opinion-piece

In [20]:
df_bert.columns = ['id', 'label', 'statement', 'subject','speaker', "job_title", 'state', 'party', 'barely_true_counts', 'false_counts',
'half_true_counts', 'mostly_true_counts', 'pants_on_fire_counts','context']
df_bert.head()

,id,label,statement,subject,speaker,job_title,state,party,barely_true_counts,false_counts,half_true_counts,mostly_true_counts,pants_on_fire_counts,context
0,10540.json,half-true,When did the decline of coal start? It started...,"energy,history,job-accomplishments",scott-surovell,State delegate,Virginia,democrat,0.0,0.0,1.0,1.0,0.0,a floor speech.
1,324.json,mostly-true,"Hillary Clinton agrees with John McCain ""by vo...",foreign-policy,barack-obama,President,Illinois,democrat,70.0,71.0,160.0,163.0,9.0,Denver
2,1123.json,false,Health care reform legislation is likely to ma...,health-care,blog-posting,NaN,NaN,none,7.0,19.0,3.0,5.0,44.0,a news release
3,9028.json,half-true,The economic turnaround started at the end of ...,"economy,jobs",charlie-crist,NaN,Florida,democrat,15.0,9.0,20.0,19.0,2.0,an interview on CNN
4,12465.json,true,The Chicago Bears have had more starting quart...,education,robin-vos,Wisconsin Assembly speaker,Wisconsin,republican,0.0,3.0,2.0,5.0,1.0,a an online opinion-piece

In [21]:
#roBERTa

from transformers import RobertaTokenizerFast

tokenizer = RobertaTokenizerFast.from_pretrained("FacebookAI/roberta-base")

/home/ulrike/.pyenv/versions/liar_project/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [22]:
from transformers import RobertaForSequenceClassification

model = RobertaForSequenceClassification.from_pretrained(
    "FacebookAI/roberta-base",
    num_labels=3,
    id2label={
        0: "CLASS_1",
        1: "CLASS_2",
        2: "CLASS_3",
    },
    label2id={
        "CLASS_1": 0,
        "CLASS_2": 1,
        "CLASS_3": 2,
    }
)

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 5275.65it/s]
[transformers] RobertaForSequenceClassification LOAD REPORT from: FacebookAI/roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
classifier.out_proj.bias   | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.out_proj.weight | MISSING    |
classifier.dense.bias      | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [23]:
print(model.roberta.embeddings.word_embeddings.weight.shape)
print(len(tokenizer))

torch.Size([50265, 768])
50265

In [24]:
df_bert["len"] = df_bert["statement"].astype(str).apply(lambda x: len(tokenizer.tokenize(x)))
df_bert[df_bert["len"] > 512]

[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (2723 > 512). Running this sequence through the model will result in indexing errors

,id,label,statement,subject,speaker,job_title,state,party,barely_true_counts,false_counts,half_true_counts,mostly_true_counts,pants_on_fire_counts,context,len
1279,1606.json,mostly-true,"Hospitals, doctors, MRIs, surgeries and so for...","elections,ethics,states",charlie-crist,NaN,Florida,democrat,15.0,9.0,20.0,19.0,2.0,a debate on Fox News Sunday,2723
6118,1993.json,true,Georgia has the most restrictive ballot access...,crime,dan-gelber,NaN,Florida,democrat,2.0,2.0,1.0,3.0,0.0,his campaign blog,1353
7549,1720.json,false,The vast majority of the money I got was from ...,"stimulus,transportation",bobby-jindal,Governor of Louisiana,Louisiana,republican,0.0,1.0,4.0,4.0,0.0,the Republican response to Obama's speech to C...,1789

In [25]:
from transformers import pipeline

pipe = pipeline(
    task="text-classification",
    model=model,
    tokenizer=tokenizer,
    truncation=True,
    max_length=512
)

In [26]:
result = pipe(df_bert["statement"].iloc[0:10].astype(str).tolist())

result

[{'label': 'CLASS_1', 'score': 0.37105226516723633},
 {'label': 'CLASS_1', 'score': 0.3719128966331482},
 {'label': 'CLASS_1', 'score': 0.37262198328971863},
 {'label': 'CLASS_1', 'score': 0.3732621669769287},
 {'label': 'CLASS_1', 'score': 0.3714362382888794},
 {'label': 'CLASS_1', 'score': 0.37246590852737427},
 {'label': 'CLASS_1', 'score': 0.36959072947502136},
 {'label': 'CLASS_1', 'score': 0.3714068830013275},
 {'label': 'CLASS_1', 'score': 0.3714105188846588},
 {'label': 'CLASS_1', 'score': 0.37087759375572205}]

deBERTa
- maybe use Quantization? to reduce memory burden

In [27]:
#! pip install tiktoken

In [28]:
#! rm -rf ~/.cache/huggingface/hub/models--microsoft--deberta-v2-xlarge-mnli

In [29]:
#! pip install sentencepiece

In [30]:
#! pip install protobuf

In [31]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

tokenizer2 = AutoTokenizer.from_pretrained("microsoft/deberta-v3-base")
model2 = AutoModelForSequenceClassification.from_pretrained("microsoft/deberta-v3-base",
    num_labels=3,
    id2label={
        0: "CLASS_1",
        1: "CLASS_2",
        2: "CLASS_3",
    },
    label2id={
        "CLASS_1": 0,
        "CLASS_2": 1,
        "CLASS_3": 2,
    }
)

Loading weights: 100%|██████████| 198/198 [00:00<00:00, 38623.02it/s]
[transformers] DebertaV2ForSequenceClassification LOAD REPORT from: microsoft/deberta-v3-base
Key                                     | Status     |
----------------------------------------+------------+-
lm_predictions.lm_head.dense.bias       | UNEXPECTED |
mask_predictions.dense.bias             | UNEXPECTED |
lm_predictions.lm_head.bias             | UNEXPECTED |
lm_predictions.lm_head.dense.weight     | UNEXPECTED |
mask_predictions.LayerNorm.bias         | UNEXPECTED |
mask_predictions.classifier.weight      | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.bias   | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight | UNEXPECTED |
mask_predictions.classifier.bias        | UNEXPECTED |
mask_predictions.dense.weight           | UNEXPECTED |
mask_predictions.LayerNorm.weight       | UNEXPECTED |
classifier.bias                         | MISSING    |
pooler.dense.bias                       | MISSING    |
pooler.dense.weight                     | MISSING    |
classifier.weight                       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [32]:
print(model2.deberta.embeddings.word_embeddings.weight.shape)
print(len(tokenizer2))

torch.Size([128100, 768])
128001

In [33]:
from transformers import pipeline

pipe2 = pipeline(
    task="text-classification",
    model=model2,
    tokenizer=tokenizer2
)

In [34]:
result2 = pipe2(df_bert["statement"].iloc[0:10].astype(str).tolist())

result2

[{'label': 'CLASS_2', 'score': 0.34991389513015747},
 {'label': 'CLASS_2', 'score': 0.3490177392959595},
 {'label': 'CLASS_2', 'score': 0.3490220904350281},
 {'label': 'CLASS_2', 'score': 0.34896913170814514},
 {'label': 'CLASS_2', 'score': 0.3493170142173767},
 {'label': 'CLASS_2', 'score': 0.34878405928611755},
 {'label': 'CLASS_2', 'score': 0.34952086210250854},
 {'label': 'CLASS_2', 'score': 0.35108909010887146},
 {'label': 'CLASS_2', 'score': 0.3506195545196533},
 {'label': 'CLASS_2', 'score': 0.350619375705719}]

from transformers import AutoModelForSequenceClassification, AutoTokenizer, BitsAndBytesConfig

model_id = "microsoft/deberta-v2-xlarge-mnli"
quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype="float16",
    bnb_4bit_use_double_quant=True,
)
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForSequenceClassification.from_pretrained(
    model_id,
    quantization_config=quantization_config,
    dtype="float16"
 device_map="auto")

inputs = tokenizer("DeBERTa-v2 is great at understanding context!", return_tensors="pt").to(model.device)
outputs = model(**inputs)
logits = outputs.logits
predicted_class_id = logits.argmax().item()
predicted_label = model.config.id2label[predicted_class_id]
print(f"Predicted label: {predicted_label}")

# train roBERTa on training data with 3 labels

In [35]:
def simplify_label(label):
    if label in ["true", "mostly-true"]:
        return "trustworthy"

    elif label == "half-true":
        return "questionable"

    else:
        return "unreliable"

In [36]:
df_bert["simple_label"] = df_bert["label"].apply(simplify_label)
df_bert.head()

,id,label,statement,subject,speaker,job_title,state,party,barely_true_counts,false_counts,half_true_counts,mostly_true_counts,pants_on_fire_counts,context,len,simple_label
0,10540.json,half-true,When did the decline of coal start? It started...,"energy,history,job-accomplishments",scott-surovell,State delegate,Virginia,democrat,0.0,0.0,1.0,1.0,0.0,a floor speech.,118,questionable
1,324.json,mostly-true,"Hillary Clinton agrees with John McCain ""by vo...",foreign-policy,barack-obama,President,Illinois,democrat,70.0,71.0,160.0,163.0,9.0,Denver,87,trustworthy
2,1123.json,false,Health care reform legislation is likely to ma...,health-care,blog-posting,NaN,NaN,none,7.0,19.0,3.0,5.0,44.0,a news release,67,unreliable
3,9028.json,half-true,The economic turnaround started at the end of ...,"economy,jobs",charlie-crist,NaN,Florida,democrat,15.0,9.0,20.0,19.0,2.0,an interview on CNN,45,questionable
4,12465.json,true,The Chicago Bears have had more starting quart...,education,robin-vos,Wisconsin Assembly speaker,Wisconsin,republican,0.0,3.0,2.0,5.0,1.0,a an online opinion-piece,129,trustworthy

In [37]:
label2id = {"trustworthy": 0, "questionable": 1, "unreliable": 2}
id2label = {v: k for k, v in label2id.items()}

df_bert["labels"] = df_bert["simple_label"].map(label2id)

In [38]:
df_bert.head()

,id,label,statement,subject,speaker,job_title,state,party,barely_true_counts,false_counts,half_true_counts,mostly_true_counts,pants_on_fire_counts,context,len,simple_label,labels
0,10540.json,half-true,When did the decline of coal start? It started...,"energy,history,job-accomplishments",scott-surovell,State delegate,Virginia,democrat,0.0,0.0,1.0,1.0,0.0,a floor speech.,118,questionable,1
1,324.json,mostly-true,"Hillary Clinton agrees with John McCain ""by vo...",foreign-policy,barack-obama,President,Illinois,democrat,70.0,71.0,160.0,163.0,9.0,Denver,87,trustworthy,0
2,1123.json,false,Health care reform legislation is likely to ma...,health-care,blog-posting,NaN,NaN,none,7.0,19.0,3.0,5.0,44.0,a news release,67,unreliable,2
3,9028.json,half-true,The economic turnaround started at the end of ...,"economy,jobs",charlie-crist,NaN,Florida,democrat,15.0,9.0,20.0,19.0,2.0,an interview on CNN,45,questionable,1
4,12465.json,true,The Chicago Bears have had more starting quart...,education,robin-vos,Wisconsin Assembly speaker,Wisconsin,republican,0.0,3.0,2.0,5.0,1.0,a an online opinion-piece,129,trustworthy,0

In [39]:
tokenizer = RobertaTokenizerFast.from_pretrained("FacebookAI/roberta-base")

In [40]:
model = RobertaForSequenceClassification.from_pretrained(
    "FacebookAI/roberta-base",
    num_labels=3,
    id2label=id2label,
    label2id=label2id
)

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 4461.91it/s]
[transformers] RobertaForSequenceClassification LOAD REPORT from: FacebookAI/roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
classifier.out_proj.bias   | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.out_proj.weight | MISSING    |
classifier.dense.bias      | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [41]:
import transformers
print(transformers.__version__)

5.9.0

In [42]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.12.0+cu130
False

In [43]:
#! pip install accelerate

In [44]:
from transformers import TrainingArguments, Trainer

training_args = TrainingArguments(
    output_dir="./roberta-3class",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=3,
    weight_decay=0.01
)

In [46]:
path = "/home/ulrike/code/navaso93/liar_project/raw_data/liar/valid.tsv"
df_valid = pd.read_csv(path , sep='\t', header = 0)
df_valid.head()

,12134.json,barely-true,We have less Americans working now than in the 70s.,"economy,jobs",vicky-hartzler,U.S. Representative,Missouri,republican,1,0,1.1,0.1,0.2,an interview with ABC17 News
0,238.json,pants-fire,"When Obama was sworn into office, he DID NOT u...","obama-birth-certificate,religion",chain-email,NaN,NaN,none,11,43,8,5,105,NaN
1,7891.json,false,Says Having organizations parading as being so...,"campaign-finance,congress,taxes",earl-blumenauer,U.S. representative,Oregon,democrat,0,1,1,1,0,a U.S. Ways and Means hearing
2,8169.json,half-true,Says nearly half of Oregons children are poor.,poverty,jim-francesconi,Member of the State Board of Higher Education,Oregon,none,0,1,1,1,0,an opinion article
3,929.json,half-true,On attacks by Republicans that various program...,"economy,stimulus",barack-obama,President,Illinois,democrat,70,71,160,163,9,interview with CBS News
4,9416.json,false,Says when armed civilians stop mass shootings ...,guns,jim-rubens,Small business owner,New Hampshire,republican,1,1,0,1,0,"in an interview at gun shop in Hudson, N.H."

In [47]:
df_valid.columns = ['id', 'label', 'statement', 'subject','speaker', "job_title", 'state', 'party', 'barely_true_counts', 'false_counts',
'half_true_counts', 'mostly_true_counts', 'pants_on_fire_counts','context']
df_valid.head()

,id,label,statement,subject,speaker,job_title,state,party,barely_true_counts,false_counts,half_true_counts,mostly_true_counts,pants_on_fire_counts,context
0,238.json,pants-fire,"When Obama was sworn into office, he DID NOT u...","obama-birth-certificate,religion",chain-email,NaN,NaN,none,11,43,8,5,105,NaN
1,7891.json,false,Says Having organizations parading as being so...,"campaign-finance,congress,taxes",earl-blumenauer,U.S. representative,Oregon,democrat,0,1,1,1,0,a U.S. Ways and Means hearing
2,8169.json,half-true,Says nearly half of Oregons children are poor.,poverty,jim-francesconi,Member of the State Board of Higher Education,Oregon,none,0,1,1,1,0,an opinion article
3,929.json,half-true,On attacks by Republicans that various program...,"economy,stimulus",barack-obama,President,Illinois,democrat,70,71,160,163,9,interview with CBS News
4,9416.json,false,Says when armed civilians stop mass shootings ...,guns,jim-rubens,Small business owner,New Hampshire,republican,1,1,0,1,0,"in an interview at gun shop in Hudson, N.H."

In [48]:
df_valid["simple_label"] = df_valid["label"].apply(simplify_label)
df_valid.head()

,id,label,statement,subject,speaker,job_title,state,party,barely_true_counts,false_counts,half_true_counts,mostly_true_counts,pants_on_fire_counts,context,simple_label
0,238.json,pants-fire,"When Obama was sworn into office, he DID NOT u...","obama-birth-certificate,religion",chain-email,NaN,NaN,none,11,43,8,5,105,NaN,unreliable
1,7891.json,false,Says Having organizations parading as being so...,"campaign-finance,congress,taxes",earl-blumenauer,U.S. representative,Oregon,democrat,0,1,1,1,0,a U.S. Ways and Means hearing,unreliable
2,8169.json,half-true,Says nearly half of Oregons children are poor.,poverty,jim-francesconi,Member of the State Board of Higher Education,Oregon,none,0,1,1,1,0,an opinion article,questionable
3,929.json,half-true,On attacks by Republicans that various program...,"economy,stimulus",barack-obama,President,Illinois,democrat,70,71,160,163,9,interview with CBS News,questionable
4,9416.json,false,Says when armed civilians stop mass shootings ...,guns,jim-rubens,Small business owner,New Hampshire,republican,1,1,0,1,0,"in an interview at gun shop in Hudson, N.H.",unreliable

In [49]:

df_valid["labels"] = df_valid["simple_label"].map(label2id)

In [50]:
df_valid.head()

,id,label,statement,subject,speaker,job_title,state,party,barely_true_counts,false_counts,half_true_counts,mostly_true_counts,pants_on_fire_counts,context,simple_label,labels
0,238.json,pants-fire,"When Obama was sworn into office, he DID NOT u...","obama-birth-certificate,religion",chain-email,NaN,NaN,none,11,43,8,5,105,NaN,unreliable,2
1,7891.json,false,Says Having organizations parading as being so...,"campaign-finance,congress,taxes",earl-blumenauer,U.S. representative,Oregon,democrat,0,1,1,1,0,a U.S. Ways and Means hearing,unreliable,2
2,8169.json,half-true,Says nearly half of Oregons children are poor.,poverty,jim-francesconi,Member of the State Board of Higher Education,Oregon,none,0,1,1,1,0,an opinion article,questionable,1
3,929.json,half-true,On attacks by Republicans that various program...,"economy,stimulus",barack-obama,President,Illinois,democrat,70,71,160,163,9,interview with CBS News,questionable,1
4,9416.json,false,Says when armed civilians stop mass shootings ...,guns,jim-rubens,Small business owner,New Hampshire,republican,1,1,0,1,0,"in an interview at gun shop in Hudson, N.H.",unreliable,2

In [ ]:
#! pip install datasets

Collecting datasets
  Downloading datasets-4.8.5-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: filelock in /home/ulrike/.pyenv/versions/3.10.6/envs/liar_project/lib/python3.10/site-packages (from datasets) (3.29.0)
Requirement already satisfied: numpy>=1.17 in /home/ulrike/.pyenv/versions/3.10.6/envs/liar_project/lib/python3.10/site-packages (from datasets) (2.2.6)
Collecting pyarrow>=21.0.0 (from datasets)
  Using cached pyarrow-24.0.0-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /home/ulrike/.pyenv/versions/3.10.6/envs/liar_project/lib/python3.10/site-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in /home/ulrike/.pyenv/versions/3.10.6/envs/liar_project/lib/python3.10/site-packages (from datasets) (2.3.3)
Requirement already satisfied: requests>=2.32.2 in /home/ulrike/.pyenv/versions/3.10.6/envs/liar_project/lib/python3.10/site-packages (from datasets) (2.34.2)
Requirement already satisfied: httpx<1.0.0 in /home/ulrike/.pyenv/versions/3.10.6/envs/liar_project/lib/python3.10/site-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /home/ulrike/.pyenv/versions/3.10.6/envs/liar_project/lib/python3.10/site-packages (from datasets) (4.67.3)
Collecting xxhash (from datasets)
  Downloading xxhash-3.7.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Collecting multiprocess<0.70.20 (from datasets)
  Downloading multiprocess-0.70.19-py310-none-any.whl.metadata (7.5 kB)
Collecting fsspec<=2026.2.0,>=2023.1.0 (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading fsspec-2026.2.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in /home/ulrike/.pyenv/versions/3.10.6/envs/liar_project/lib/python3.10/site-packages (from datasets) (1.17.0)
Requirement already satisfied: packaging in /home/ulrike/.pyenv/versions/3.10.6/envs/liar_project/lib/python3.10/site-packages (from datasets) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /home/ulrike/.pyenv/versions/3.10.6/envs/liar_project/lib/python3.10/site-packages (from datasets) (6.0.3)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1 (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading aiohttp-3.14.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (8.3 kB)
Requirement already satisfied: anyio in /home/ulrike/.pyenv/versions/3.10.6/envs/liar_project/lib/python3.10/site-packages (from httpx<1.0.0->datasets) (4.13.0)
Requirement already satisfied: certifi in /home/ulrike/.pyenv/versions/3.10.6/envs/liar_project/lib/python3.10/site-packages (from httpx<1.0.0->datasets) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /home/ulrike/.pyenv/versions/3.10.6/envs/liar_project/lib/python3.10/site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /home/ulrike/.pyenv/versions/3.10.6/envs/liar_project/lib/python3.10/site-packages (from httpx<1.0.0->datasets) (3.17)
Requirement already satisfied: h11>=0.16 in /home/ulrike/.pyenv/versions/3.10.6/envs/liar_project/lib/python3.10/site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: click>=8.4.0 in /home/ulrike/.pyenv/versions/3.10.6/envs/liar_project/lib/python3.10/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (8.4.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /home/ulrike/.pyenv/versions/3.10.6/envs/liar_project/lib/python3.10/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.5.0)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in /home/ulrike/.pyenv/versions/3.10.6/envs/liar_project/lib/python3.10/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (0.25.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /home/ulrike/.pyenv/versions/3.10.6/envs/liar_project/lib/python3.10/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.15.0)
Requirement already satisfied: shellingham>=1.3.0 in /home/ulrike/.pyenv/versions/3.10.6/envs/liar_project/lib/python3.10/site-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /home/ulrike/.pyenv/versions/3.10.6/envs/liar_project/lib/python3.10/site-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /home/ulrike/.pyenv/versions/3.10.6/envs/liar_project/lib/python3.10/site-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (0.0.4)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached aiohappyeyeballs-2.6.2-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Collecting async-timeout<6.0,>=4.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached async_timeout-5.0.1-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: attrs>=17.3.0 in /home/ulrike/.pyenv/versions/3.10.6/envs/liar_project/lib/python3.10/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (26.1.0)
Collecting frozenlist>=1.1.1 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading frozenlist-1.8.0-cp310-cp310-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (20 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading multidict-6.7.1-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.3 kB)
Collecting propcache>=0.2.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading propcache-0.5.2-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (16 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading yarl-1.24.2-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (94 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/ulrike/.pyenv/versions/3.10.6/envs/liar_project/lib/python3.10/site-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in /home/ulrike/.pyenv/versions/3.10.6/envs/liar_project/lib/python3.10/site-packages (from requests>=2.32.2->datasets) (2.7.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/ulrike/.pyenv/versions/3.10.6/envs/liar_project/lib/python3.10/site-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/ulrike/.pyenv/versions/3.10.6/envs/liar_project/lib/python3.10/site-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /home/ulrike/.pyenv/versions/3.10.6/envs/liar_project/lib/python3.10/site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (0.1.2)
Requirement already satisfied: exceptiongroup>=1.0.2 in /home/ulrike/.pyenv/versions/3.10.6/envs/liar_project/lib/python3.10/site-packages (from anyio->httpx<1.0.0->datasets) (1.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/ulrike/.pyenv/versions/3.10.6/envs/liar_project/lib/python3.10/site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/ulrike/.pyenv/versions/3.10.6/envs/liar_project/lib/python3.10/site-packages (from pandas->datasets) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in /home/ulrike/.pyenv/versions/3.10.6/envs/liar_project/lib/python3.10/site-packages (from pandas->datasets) (2026.2)
Requirement already satisfied: six>=1.5 in /home/ulrike/.pyenv/versions/3.10.6/envs/liar_project/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading datasets-4.8.5-py3-none-any.whl (528 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 529.0/529.0 kB 6.8 MB/s  0:00:00
Downloading fsspec-2026.2.0-py3-none-any.whl (202 kB)
Downloading multiprocess-0.70.19-py310-none-any.whl (134 kB)
Downloading aiohttp-3.14.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 10.9 MB/s  0:00:00
Using cached async_timeout-5.0.1-py3-none-any.whl (6.2 kB)
Downloading multidict-6.7.1-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (243 kB)
Downloading yarl-1.24.2-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (106 kB)
Using cached aiohappyeyeballs-2.6.2-py3-none-any.whl (15 kB)
Using cached aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Downloading frozenlist-1.8.0-cp310-cp310-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (219 kB)
Downloading propcache-0.5.2-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (60 kB)
Using cached pyarrow-24.0.0-cp310-cp310-manylinux_2_28_x86_64.whl (48.8 MB)
Downloading xxhash-3.7.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (193 kB)
Installing collected packages: xxhash, pyarrow, propcache, multiprocess, multidict, fsspec, frozenlist, async-timeout, aiohappyeyeballs, yarl, aiosignal, aiohttp, datasets
  Attempting uninstall: fsspec━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/13 [multidict]ss]
    Found existing installation: fsspec 2026.4.0━━━━━━━━━━━━━━  4/13 [multidict]
    Uninstalling fsspec-2026.4.0:0m━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/13 [multidict]
      Successfully uninstalled fsspec-2026.4.0━━━━━━━━━━━━━━━━  4/13 [multidict]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13/13 [datasets]/13 [datasets]t]
Successfully installed aiohappyeyeballs-2.6.2 aiohttp-3.14.0 aiosignal-1.4.0 async-timeout-5.0.1 datasets-4.8.5 frozenlist-1.8.0 fsspec-2026.2.0 multidict-6.7.1 multiprocess-0.70.19 propcache-0.5.2 pyarrow-24.0.0 xxhash-3.7.0 yarl-1.24.2

In [54]:
from datasets import Dataset

train_ds = Dataset.from_pandas(df_bert)
valid_ds = Dataset.from_pandas(df_valid)

In [55]:
def tokenize(batch):
    return tokenizer(
        batch["statement"],
        truncation=True,
        padding="max_length",
        max_length=128
    )

In [56]:
train_ds = train_ds.map(tokenize, batched=True)
valid_ds = valid_ds.map(tokenize, batched=True)

Map: 100%|██████████| 10239/10239 [00:01<00:00, 9480.00 examples/s]
Map: 100%|██████████| 1283/1283 [00:00<00:00, 12090.13 examples/s]

In [58]:
train_ds.info

DatasetInfo(features={'id': Value('string'), 'label': Value('string'), 'statement': Value('string'), 'subject': Value('string'), 'speaker': Value('string'), 'job_title': Value('string'), 'state': Value('string'), 'party': Value('string'), 'barely_true_counts': Value('float64'), 'false_counts': Value('float64'), 'half_true_counts': Value('float64'), 'mostly_true_counts': Value('float64'), 'pants_on_fire_counts': Value('float64'), 'context': Value('string'), 'len': Value('int64'), 'simple_label': Value('string'), 'labels': Value('int64'), 'input_ids': List(Value('int32')), 'attention_mask': List(Value('int8'))})

In [59]:
needed = {"input_ids", "attention_mask", "labels"}

train_ds = train_ds.remove_columns([c for c in train_ds.column_names if c not in needed])
valid_ds = valid_ds.remove_columns([c for c in valid_ds.column_names if c not in needed])

In [60]:
train_ds.set_format(type="torch", columns=["input_ids", "attention_mask", "labels"])
valid_ds.set_format(type="torch", columns=["input_ids", "attention_mask", "labels"])

In [ ]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_ds,
    eval_dataset=valid_ds
)

trainer.train()

/home/ulrike/.pyenv/versions/liar_project/lib/python3.10/site-packages/torch/utils/data/dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)